# Netlify Configuration for Static Site
[build]
  command = "chmod +x build-static.sh && ./build-static.sh"
  publish = "dist-static"

[build.environment]
  NODE_VERSION = "20"

# Redirect rules - no SPA routing needed
[[redirects]]
  from = "/lms"
  to = "/lms.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/demo-site.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
