services:
  # Static Site - HTML Pages Only (Working)
  - type: web
    name: elevate-site
    env: node
    region: oregon
    plan: free
    buildCommand: npm install express
    startCommand: node server-simple.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health

  # Backend API (Separate Service)
  - type: web
    name: elevate-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: elevate-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: elevate-db
    databaseName: elevate
    user: elevate
    plan: free
