name: AI Assistant Worker

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      task:
        description: 'Task for AI to perform'
        required: true
        type: choice
        options:
          - 'Fix failing tests'
          - 'Update dependencies'
          - 'Optimize performance'
          - 'Fix security issues'
          - 'Generate documentation'

jobs:
  ai-code-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AI Code Review with OpenAI
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          model: gpt-4
          review_comment_lgtm: true

  ai-auto-fix:
    name: AI Auto-Fix Issues
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ai-fix' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests to identify failures
        id: test
        run: |
          npm test > test-output.txt 2>&1 || true
          cat test-output.txt

      - name: AI analyze and fix
        if: failure()
        run: |
          # Use AI to analyze test failures and suggest fixes
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {
                  "role": "system",
                  "content": "You are an expert developer. Analyze test failures and provide fixes."
                },
                {
                  "role": "user",
                  "content": "Test output: $(cat test-output.txt). Provide fixes."
                }
              ]
            }' > ai-response.json

      - name: Apply AI suggestions
        run: |
          # Parse AI response and apply fixes
          echo "AI suggestions received, applying fixes..."
          # This would contain logic to parse and apply fixes

      - name: Commit fixes
        run: |
          git config user.name "AI Assistant"
          git config user.email "ai@elevateforhumanity.org"
          git add -A
          git commit -m "🤖 AI auto-fix: Resolved test failures

          Applied AI-suggested fixes
          
          Co-authored-by: Ona <no-reply@ona.com>" || echo "No changes to commit"
          git push origin ${{ github.head_ref }}

  ai-dependency-updates:
    name: AI Dependency Updates
    runs-on: ubuntu-latest
    if: github.event.label.name == 'dependencies' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for updates
        run: |
          npm outdated > outdated.txt || true
          cat outdated.txt

      - name: AI analyze updates
        run: |
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {
                  "role": "system",
                  "content": "You are a dependency management expert. Analyze outdated packages and recommend safe updates."
                },
                {
                  "role": "user",
                  "content": "Outdated packages: $(cat outdated.txt). Which should be updated?"
                }
              ]
            }' > ai-deps.json

      - name: Update safe dependencies
        run: |
          npm update
          npm audit fix

      - name: Create PR with updates
        run: |
          git config user.name "AI Assistant"
          git config user.email "ai@elevateforhumanity.org"
          git checkout -b ai-dependency-updates-$(date +%s)
          git add -A
          git commit -m "🤖 AI dependency updates

          Updated dependencies based on AI analysis
          
          Co-authored-by: Ona <no-reply@ona.com>"
          git push origin HEAD
          gh pr create --title "🤖 AI Dependency Updates" \
                       --body "Automated dependency updates analyzed by AI" \
                       --label "dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ai-documentation:
    name: AI Documentation Generator
    runs-on: ubuntu-latest
    if: github.event.label.name == 'documentation' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate documentation with AI
        run: |
          # Scan codebase
          find src -name "*.ts" -o -name "*.tsx" > files.txt
          
          # Use AI to generate docs
          for file in $(cat files.txt); do
            curl -X POST https://api.openai.com/v1/chat/completions \
              -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d "{
                \"model\": \"gpt-4\",
                \"messages\": [
                  {
                    \"role\": \"system\",
                    \"content\": \"Generate comprehensive JSDoc comments for this code.\"
                  },
                  {
                    \"role\": \"user\",
                    \"content\": \"$(cat $file)\"
                  }
                ]
              }" > "${file}.docs.json"
          done

      - name: Commit documentation
        run: |
          git config user.name "AI Assistant"
          git config user.email "ai@elevateforhumanity.org"
          git add -A
          git commit -m "📚 AI-generated documentation

          Added comprehensive documentation
          
          Co-authored-by: Ona <no-reply@ona.com>" || echo "No changes"
          git push origin main

  ai-performance-optimization:
    name: AI Performance Optimization
    runs-on: ubuntu-latest
    if: github.event.label.name == 'performance' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run performance audit
        run: |
          npm run build
          npx lighthouse https://elevateforhumanity.pages.dev \
            --output=json \
            --output-path=./lighthouse-report.json

      - name: AI analyze performance
        run: |
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"gpt-4\",
              \"messages\": [
                {
                  \"role\": \"system\",
                  \"content\": \"You are a performance optimization expert. Analyze Lighthouse report and suggest improvements.\"
                },
                {
                  \"role\": \"user\",
                  \"content\": \"$(cat lighthouse-report.json)\"
                }
              ]
            }" > ai-perf.json

      - name: Create optimization issue
        run: |
          gh issue create \
            --title "🚀 AI Performance Optimization Suggestions" \
            --body "$(cat ai-perf.json)" \
            --label "performance"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ai-security-scan:
    name: AI Security Scanner
    runs-on: ubuntu-latest
    if: github.event.label.name == 'security' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit
        run: |
          npm audit --json > audit.json || true
          cat audit.json

      - name: AI analyze security issues
        run: |
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"gpt-4\",
              \"messages\": [
                {
                  \"role\": \"system\",
                  \"content\": \"You are a security expert. Analyze npm audit results and provide fixes.\"
                },
                {
                  \"role\": \"user\",
                  \"content\": \"$(cat audit.json)\"
                }
              ]
            }" > ai-security.json

      - name: Auto-fix security issues
        run: |
          npm audit fix --force
          git config user.name "AI Assistant"
          git config user.email "ai@elevateforhumanity.org"
          git add -A
          git commit -m "🔒 AI security fixes

          Applied automated security patches
          
          Co-authored-by: Ona <no-reply@ona.com>" || echo "No fixes needed"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
